# Generated by Django 3.1 on 2020-09-03 08:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_blogcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogComment',
            new_name='PostComment',
        ),
    ]
